### ISSUE TITLE
request.py的使用方法，在readme是否没说清楚，请问cate.txt文件的作用是什么？

### ISSUE THREAD

**Issue by Hollywood3** [LawRefBook/Laws#6]
报错如下：
Traceback (most recent call last):
  File "E:\Laws-master\scripts\request.py", line 233, in <module>
    main()
  File "E:\Laws-master\scripts\request.py", line 197, in main
    req = LawParser()
  File "E:\Laws-master\scripts\request.py", line 51, in __init__
    self.__init()
  File "E:\Laws-master\scripts\request.py", line 55, in __init
    with open("./cate.txt", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './cate.txt'

**Comment by mechigonft** [comment]
你好，同样的问题，请问解决了吗？

**Comment by RanKKI** [comment]
之前一些法律可以自动分类，但后续更新的法律，因为找不到数据，只能手动分类了。 

代码已修复。
